// <auto-generated />
namespace CoinTrust.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class user_seed_test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_seed_test));
        
        string IMigrationMetadata.Id
        {
            get { return "201801240948043_user_seed_test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
