// <auto-generated />
namespace CoinTrust.Migrations.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editmodelaccountinfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editmodelaccountinfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201803180503496_edit-model-accountinfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
