// <auto-generated />
namespace CoinTrust.Migrations.TestCarMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class testcar1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testcar1));
        
        string IMigrationMetadata.Id
        {
            get { return "201802101052386_test-car-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
